# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en
  label: English
  weight: 10
  params:
    locale:
      date_format: 'Jan 2, 2006'
      time_format: '3:04 PM'
      address_format: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: Kunieda Lab
  menu:
    main:
      - name: News
        url: news
        weight: 10
      - name: Research
        url: research
        weight: 20
      - name: Publication
        url: publication
        weight: 30
      - name: Member
        url: member
        weight: 40
      - name: Contact
        url: contact
        weight: 50
#      - name: Link
#        url: link
#        weight: 60

ja:
  locale: ja
  label: Japanese
  weight: 5
  params:
    locale:
      date_format: '2006年01月02日'
      time_format: '15:04'
      address_format: ja-jp
  contentDir: content/ja
  title: 國枝研（生体情報学II）
  menu:
    main:
    - name: News
      url: news
      weight: 10
    - name: 研究内容
      url: research
      identifier: research
      weight: 20
    - name: クマムシとは？
      parent: research
      identifier: tardigrade
      url: tardigrade
      weight: 10
    - name: クマムシの耐性メカニズム
      parent: research
      identifier: tolerance
      url: tolerance
      weight: 20
    - name: ワムシの耐性
      parent: research
      identifier: rotifer
      url: rotifer
      weight: 30
    - name: 業績
      url: publication
      weight: 30
    - name: メンバー
      url: member
      weight: 40
    - name: コンタクト
      url: contact
      weight: 50
#    - name: リンク
#      url: link
#      weight: 60

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
