# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

en:

    - name: News2
      url: news
      weight: 10
    - name: Research2
      url: research
      weight: 20
    - name: Publication2
      url: publication
      weight: 30
    - name: Member2
      url: member
      weight: 40
    - name: Contact2
      url: contact
      weight: 50
    - name: Link2
      url: link
      weight: 60

ja:

    - name: ニュース
      url: news
      weight: 10
    - name: 研究内容
      url: research
      weight: 20
    - name: 研究業績
      url: publication
      weight: 30
    - name: メンバー
      url: member
      weight: 40
    - name: コンタクト
      url: contact
      weight: 50
    - name: リンク
      url: link
      weight: 60
